'use client';

import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Code, 
  Settings, 
  Eye, 
  FileText, 
  Zap, 
  Database,
  Palette,
  GitBranch,
  Play,
  Save,
  Download
} from 'lucide-react';

interface ModuleConfig {
  id: string;
  name: string;
  version: string;
  description: string;
  author: string;
  category: 'education' | 'productivity' | 'creative' | 'research' | 'utility';
  features: string[];
  aiModels: string[];
  theme: 'dark' | 'light' | 'auto';
  database: boolean;
  realtime: boolean;
  kiroIntegration: {
    specs: boolean;
    hooks: boolean;
    steering: boolean;
  };
}

interface DeveloperConsoleProps {
  onModuleGenerate: (config: ModuleConfig) => void;
  isGenerating: boolean;
}

export default function DeveloperConsole({ onModuleGenerate, isGenerating }: DeveloperConsoleProps) {
  const [activeTab, setActiveTab] = useState<'config' | 'preview' | 'docs' | 'settings'>('config');
  const [config, setConfig] = useState<ModuleConfig>({
    id: '',
    name: '',
    version: '1.0.0',
    description: '',
    author: '',
    category: 'education',
    features: [],
    aiModels: ['gpt-4'],
    theme: 'dark',
    database: false,
    realtime: false,
    kiroIntegration: {
      specs: true,
      hooks: true,
      steering: true
    }
  });

  const [previewCode, setPreviewCode] = useState('');
  const [generatedDocs, setGeneratedDocs] = useState('');

  // Auto-generate ID from name
  useEffect(() => {
    if (config.name) {
      const id = config.name
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, '')
        .replace(/\s+/g, '-');
      setConfig(prev => ({ ...prev, id }));
    }
  }, [config.name]);

  // Generate preview code
  useEffect(() => {
    if (config.name && config.category) {
      generatePreviewCode();
      generateDocumentation();
    }
  }, [config]);

  const generatePreviewCode = () => {
    const code = `// 🎃 ${config.name} Module
// Generated by GhostFrame Developer Console

import { KiroModule, ModuleProcessor } from '@ghostframe/core';

export interface ${toPascalCase(config.id)}Config {
  ${config.database ? 'database: DatabaseConfig;' : ''}
  ${config.realtime ? 'realtime: RealtimeConfig;' : ''}
  aiModels: string[];
  theme: '${config.theme}';
}

export class ${toPascalCase(config.id)}Processor implements ModuleProcessor {
  constructor(private config: ${toPascalCase(config.id)}Config) {}

  async process(input: any): Promise<any> {
    // Your ${config.category} processing logic here
    ${generateProcessingLogic(config.category)}
  }

  ${config.realtime ? `
  async streamProcess(input: any): Promise<AsyncGenerator<any>> {
    // Real-time streaming implementation
    yield* this.generateStreamingResponse(input);
  }` : ''}
}

// Kiro Integration
export const ${config.id}Module: KiroModule = {
  id: '${config.id}',
  name: '${config.name}',
  version: '${config.version}',
  category: '${config.category}',
  processor: ${toPascalCase(config.id)}Processor,
  ${config.kiroIntegration.specs ? 'specs: true,' : ''}
  ${config.kiroIntegration.hooks ? 'hooks: true,' : ''}
  ${config.kiroIntegration.steering ? 'steering: true,' : ''}
};`;

    setPreviewCode(code);
  };

  const generateDocumentation = () => {
    const docs = `# ${config.name}

${config.description}

## Features

${config.features.map(feature => `- ${feature}`).join('\n')}

## Configuration

\`\`\`typescript
interface ${toPascalCase(config.id)}Config {
  aiModels: string[];
  theme: '${config.theme}';
  ${config.database ? 'database: DatabaseConfig;' : ''}
  ${config.realtime ? 'realtime: RealtimeConfig;' : ''}
}
\`\`\`

## Usage

\`\`\`typescript
import { ${config.id}Module } from './${config.id}';

const processor = new ${toPascalCase(config.id)}Processor(config);
const result = await processor.process(input);
\`\`\`

## Kiro Integration

${config.kiroIntegration.specs ? '✅ Specifications included' : '❌ No specifications'}
${config.kiroIntegration.hooks ? '✅ Automation hooks included' : '❌ No hooks'}
${config.kiroIntegration.steering ? '✅ AI steering included' : '❌ No steering'}
`;

    setGeneratedDocs(docs);
  };

  const tabs = [
    { id: 'config', label: 'Configuration', icon: Settings },
    { id: 'preview', label: 'Code Preview', icon: Eye },
    { id: 'docs', label: 'Documentation', icon: FileText },
    { id: 'settings', label: 'Advanced', icon: Code }
  ];

  const categories = [
    { value: 'education', label: 'Education', icon: '🎓', description: 'Learning and teaching tools' },
    { value: 'productivity', label: 'Productivity', icon: '⚡', description: 'Workflow and efficiency' },
    { value: 'creative', label: 'Creative', icon: '🎨', description: 'Art and content creation' },
    { value: 'research', label: 'Research', icon: '🔬', description: 'Data analysis and insights' },
    { value: 'utility', label: 'Utility', icon: '🛠️', description: 'General purpose tools' }
  ];

  const aiModels = [
    { value: 'gpt-4', label: 'GPT-4', provider: 'OpenAI' },
    { value: 'gpt-3.5-turbo', label: 'GPT-3.5 Turbo', provider: 'OpenAI' },
    { value: 'claude-3', label: 'Claude 3', provider: 'Anthropic' },
    { value: 'gemini-pro', label: 'Gemini Pro', provider: 'Google' },
    { value: 'mistral-large', label: 'Mistral Large', provider: 'Mistral' }
  ];

  return (
    <div className="min-h-screen bg-midnight-black text-ghost-white">
      {/* Header */}
      <div className="border-b border-spectral-green/20 bg-midnight-black/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <div className="flex items-center space-x-2">
                <Code className="h-6 w-6 text-spectral-green" />
                <h1 className="text-xl font-bold">Developer Console</h1>
              </div>
              <div className="text-sm text-gray-400">
                {config.name || 'Untitled Module'} v{config.version}
              </div>
            </div>
            
            <div className="flex items-center space-x-3">
              <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => onModuleGenerate(config)}
                disabled={!config.name || !config.description || isGenerating}
                className="ghost-button-primary flex items-center space-x-2 px-4 py-2 disabled:opacity-50"
              >
                {isGenerating ? (
                  <>
                    <div className="animate-spin rounded-full h-4 w-4 border-2 border-spectral-green border-t-transparent" />
                    <span>Generating...</span>
                  </>
                ) : (
                  <>
                    <Play className="h-4 w-4" />
                    <span>Generate Module</span>
                  </>
                )}
              </motion.button>
            </div>
          </div>
        </div>
      </div>

      {/* Tab Navigation */}
      <div className="border-b border-spectral-green/10">
        <div className="max-w-7xl mx-auto px-6">
          <div className="flex space-x-8">
            {tabs.map((tab) => {
              const Icon = tab.icon;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id as any)}
                  className={`flex items-center space-x-2 py-4 px-2 border-b-2 transition-colors ${
                    activeTab === tab.id
                      ? 'border-spectral-green text-spectral-green'
                      : 'border-transparent text-gray-400 hover:text-ghost-white'
                  }`}
                >
                  <Icon className="h-4 w-4" />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-7xl mx-auto px-6 py-8">
        <AnimatePresence mode="wait">
          {activeTab === 'config' && (
            <motion.div
              key="config"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="space-y-8"
            >
              {/* Basic Information */}
              <div className="bg-midnight-black/30 border border-spectral-green/20 rounded-xl p-6">
                <h2 className="text-xl font-bold mb-6 flex items-center">
                  <FileText className="h-5 w-5 text-spectral-green mr-2" />
                  Basic Information
                </h2>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Module Name *
                    </label>
                    <input
                      type="text"
                      value={config.name}
                      onChange={(e) => setConfig(prev => ({ ...prev, name: e.target.value }))}
                      placeholder="My Awesome AI Module"
                      className="haunted-input w-full"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Version
                    </label>
                    <input
                      type="text"
                      value={config.version}
                      onChange={(e) => setConfig(prev => ({ ...prev, version: e.target.value }))}
                      className="haunted-input w-full"
                    />
                  </div>

                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Description *
                    </label>
                    <textarea
                      value={config.description}
                      onChange={(e) => setConfig(prev => ({ ...prev, description: e.target.value }))}
                      placeholder="Describe what your module does..."
                      rows={3}
                      className="haunted-input w-full"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">
                      Author
                    </label>
                    <input
                      type="text"
                      value={config.author}
                      onChange={(e) => setConfig(prev => ({ ...prev, author: e.target.value }))}
                      placeholder="Your Name"
                      className="haunted-input w-full"
                    />
                  </div>
                </div>
              </div>

              {/* Category Selection */}
              <div className="bg-midnight-black/30 border border-spectral-green/20 rounded-xl p-6">
                <h2 className="text-xl font-bold mb-6 flex items-center">
                  <Palette className="h-5 w-5 text-spectral-green mr-2" />
                  Category & Features
                </h2>
                
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-6">
                  {categories.map((category) => (
                    <motion.button
                      key={category.value}
                      whileHover={{ scale: 1.02 }}
                      whileTap={{ scale: 0.98 }}
                      onClick={() => setConfig(prev => ({ ...prev, category: category.value as any }))}
                      className={`p-4 rounded-lg border-2 transition-all ${
                        config.category === category.value
                          ? 'border-spectral-green bg-spectral-green/10'
                          : 'border-gray-600 hover:border-spectral-green/50'
                      }`}
                    >
                      <div className="text-2xl mb-2">{category.icon}</div>
                      <div className="font-semibold">{category.label}</div>
                      <div className="text-sm text-gray-400">{category.description}</div>
                    </motion.button>
                  ))}
                </div>
              </div>

              {/* AI Models */}
              <div className="bg-midnight-black/30 border border-spectral-green/20 rounded-xl p-6">
                <h2 className="text-xl font-bold mb-6 flex items-center">
                  <Zap className="h-5 w-5 text-spectral-green mr-2" />
                  AI Models
                </h2>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {aiModels.map((model) => (
                    <label key={model.value} className="flex items-center space-x-3 p-3 rounded-lg border border-gray-600 hover:border-spectral-green/50 cursor-pointer">
                      <input
                        type="checkbox"
                        checked={config.aiModels.includes(model.value)}
                        onChange={(e) => {
                          if (e.target.checked) {
                            setConfig(prev => ({ ...prev, aiModels: [...prev.aiModels, model.value] }));
                          } else {
                            setConfig(prev => ({ ...prev, aiModels: prev.aiModels.filter(m => m !== model.value) }));
                          }
                        }}
                        className="rounded border-gray-600 text-spectral-green focus:ring-spectral-green"
                      />
                      <div>
                        <div className="font-medium">{model.label}</div>
                        <div className="text-sm text-gray-400">{model.provider}</div>
                      </div>
                    </label>
                  ))}
                </div>
              </div>
            </motion.div>
          )}

          {activeTab === 'preview' && (
            <motion.div
              key="preview"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
            >
              <div className="bg-midnight-black/30 border border-spectral-green/20 rounded-xl p-6">
                <h2 className="text-xl font-bold mb-6 flex items-center">
                  <Eye className="h-5 w-5 text-spectral-green mr-2" />
                  Generated Code Preview
                </h2>
                
                <div className="bg-black/50 border border-spectral-green/30 rounded-lg p-4 overflow-x-auto">
                  <pre className="text-sm text-spectral-green">
                    <code>{previewCode}</code>
                  </pre>
                </div>
              </div>
            </motion.div>
          )}

          {activeTab === 'docs' && (
            <motion.div
              key="docs"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
            >
              <div className="bg-midnight-black/30 border border-spectral-green/20 rounded-xl p-6">
                <h2 className="text-xl font-bold mb-6 flex items-center">
                  <FileText className="h-5 w-5 text-spectral-green mr-2" />
                  Auto-Generated Documentation
                </h2>
                
                <div className="bg-black/50 border border-spectral-green/30 rounded-lg p-4">
                  <pre className="text-sm text-gray-300 whitespace-pre-wrap">
                    {generatedDocs}
                  </pre>
                </div>
              </div>
            </motion.div>
          )}

          {activeTab === 'settings' && (
            <motion.div
              key="settings"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -20 }}
              className="space-y-8"
            >
              {/* Advanced Features */}
              <div className="bg-midnight-black/30 border border-spectral-green/20 rounded-xl p-6">
                <h2 className="text-xl font-bold mb-6 flex items-center">
                  <Settings className="h-5 w-5 text-spectral-green mr-2" />
                  Advanced Features
                </h2>
                
                <div className="space-y-4">
                  <label className="flex items-center space-x-3">
                    <input
                      type="checkbox"
                      checked={config.database}
                      onChange={(e) => setConfig(prev => ({ ...prev, database: e.target.checked }))}
                      className="rounded border-gray-600 text-spectral-green focus:ring-spectral-green"
                    />
                    <div>
                      <div className="font-medium">Database Integration</div>
                      <div className="text-sm text-gray-400">Enable persistent data storage</div>
                    </div>
                  </label>

                  <label className="flex items-center space-x-3">
                    <input
                      type="checkbox"
                      checked={config.realtime}
                      onChange={(e) => setConfig(prev => ({ ...prev, realtime: e.target.checked }))}
                      className="rounded border-gray-600 text-spectral-green focus:ring-spectral-green"
                    />
                    <div>
                      <div className="font-medium">Real-time Processing</div>
                      <div className="text-sm text-gray-400">Enable streaming and live updates</div>
                    </div>
                  </label>
                </div>
              </div>

              {/* Kiro Integration */}
              <div className="bg-midnight-black/30 border border-spectral-green/20 rounded-xl p-6">
                <h2 className="text-xl font-bold mb-6 flex items-center">
                  <GitBranch className="h-5 w-5 text-spectral-green mr-2" />
                  Kiro Integration
                </h2>
                
                <div className="space-y-4">
                  <label className="flex items-center space-x-3">
                    <input
                      type="checkbox"
                      checked={config.kiroIntegration.specs}
                      onChange={(e) => setConfig(prev => ({ 
                        ...prev, 
                        kiroIntegration: { ...prev.kiroIntegration, specs: e.target.checked }
                      }))}
                      className="rounded border-gray-600 text-spectral-green focus:ring-spectral-green"
                    />
                    <div>
                      <div className="font-medium">Specifications</div>
                      <div className="text-sm text-gray-400">Auto-generate requirements, design, and tasks</div>
                    </div>
                  </label>

                  <label className="flex items-center space-x-3">
                    <input
                      type="checkbox"
                      checked={config.kiroIntegration.hooks}
                      onChange={(e) => setConfig(prev => ({ 
                        ...prev, 
                        kiroIntegration: { ...prev.kiroIntegration, hooks: e.target.checked }
                      }))}
                      className="rounded border-gray-600 text-spectral-green focus:ring-spectral-green"
                    />
                    <div>
                      <div className="font-medium">Automation Hooks</div>
                      <div className="text-sm text-gray-400">Event-driven workflows and triggers</div>
                    </div>
                  </label>

                  <label className="flex items-center space-x-3">
                    <input
                      type="checkbox"
                      checked={config.kiroIntegration.steering}
                      onChange={(e) => setConfig(prev => ({ 
                        ...prev, 
                        kiroIntegration: { ...prev.kiroIntegration, steering: e.target.checked }
                      }))}
                      className="rounded border-gray-600 text-spectral-green focus:ring-spectral-green"
                    />
                    <div>
                      <div className="font-medium">AI Steering</div>
                      <div className="text-sm text-gray-400">Behavior guidelines and quality control</div>
                    </div>
                  </label>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

// Helper functions
function toPascalCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]/g, ' ')
    .split(' ')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}

function generateProcessingLogic(category: string): string {
  switch (category) {
    case 'education':
      return `
    // Educational content processing
    const questions = await this.generateQuestions(input);
    return { questions, analytics: this.getAnalytics(input) };`;
    case 'creative':
      return `
    // Creative content generation
    const story = await this.generateStory(input);
    return { story, characters: this.extractCharacters(story) };`;
    case 'productivity':
      return `
    // Productivity enhancement
    const optimized = await this.optimizeWorkflow(input);
    return { optimized, suggestions: this.getSuggestions(input) };`;
    case 'research':
      return `
    // Research and analysis
    const insights = await this.analyzeData(input);
    return { insights, visualizations: this.createCharts(insights) };`;
    default:
      return `
    // General purpose processing
    const result = await this.processInput(input);
    return { result, metadata: this.getMetadata(input) };`;
  }
}